kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vol2
  namespace: app
  annotations:
     trident.netapp.io/snapshotPolicy: "default"
     trident.netapp.io/snapshotDirectory: "true"
     trident.netapp.io/reclaimPolicy: "Retain"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas
  resources:
    requests:
      storage: 2Gi
