apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-nas-us-east-1
provisioner: csi.trident.netapp.io
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - us-east-1a
    - us-east-1c
  - key: topology.kubernetes.io/region
    values:
    - us-east-1
parameters:
  fsType: "ext4"
allowVolumeExpansion: True